name: Test Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: echo "Build"

  test:
    runs-on: ubuntu-latest

    steps:
    - run: echo "Test"